=== EgorKin/usbdm-eclipse-makefiles-build/PackageFiles/Stationery/Packages/180.ARM_Peripherals/Hardware/peripherals/_menu.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ENTITY % gui_items        "(xi:include|category|indexedCategory|constant|floatOption|intOption|bitmaskOption|choiceOption|binaryOption|irqOption|stringOption|numericListOption|pinListOption|aliasOption|signals)" >
<!ENTITY % structure_items  "(xi:include|section|list)" >
<!ENTITY % control_items    "(xi:include|template|validate|projectActionList)" >

<!-- Include another file -->
<!ELEMENT xi:include EMPTY>
   <!ATTLIST xi:include href      CDATA        #REQUIRED>

<!-- Root fileElement -->
<!ELEMENT peripheralPage ((%structure_items;|%gui_items;|%control_items;)*) >
   <!ATTLIST peripheralPage xmlns:xi     CDATA        #IMPLIED>
   <!ATTLIST peripheralPage name         CDATA        #REQUIRED>
   <!ATTLIST peripheralPage description  CDATA        #REQUIRED>
   <!ATTLIST peripheralPage toolTip      CDATA        #IMPLIED>

<!ELEMENT fragment ANY >
   <!ATTLIST fragment xmlns:xi CDATA #IMPLIED>

<!ELEMENT list (((%structure_items;),(%control_items;)*)|(%gui_items;|%control_items;)*) >
   <!ATTLIST list name         CDATA        #IMPLIED>
   <!ATTLIST list description  CDATA        #IMPLIED>

<!ELEMENT section (((%structure_items;),(%control_items;)*)|(%gui_items;|%control_items;)*) >
   <!ATTLIST section name         CDATA        #IMPLIED>

<!ELEMENT indexedCategory ((%gui_items;)*) >
   <!ATTLIST indexedCategory xmlns:xi     CDATA        #IMPLIED>
   <!ATTLIST indexedCategory name         ID           #REQUIRED>
   <!ATTLIST indexedCategory description  CDATA        #REQUIRED>
   <!ATTLIST indexedCategory toolTip      CDATA        #IMPLIED>
   <!ATTLIST indexedCategory dim          CDATA        "0" >
   <!ATTLIST indexedCategory value        CDATA        #IMPLIED>
   <!ATTLIST indexedCategory constant     (false|true) "false">

<!ELEMENT category ((%gui_items;|template)*) >
   <!ATTLIST category xmlns:xi     CDATA        #IMPLIED>
   <!ATTLIST category name         CDATA        #REQUIRED>
   <!ATTLIST category description  CDATA        #REQUIRED>
   <!ATTLIST category toolTip      CDATA        #IMPLIED>

<!ELEMENT intOption EMPTY >
   <!ATTLIST intOption constant     (false|true) "false">
   <!ATTLIST intOption name         ID           #REQUIRED>
   <!ATTLIST intOption key          CDATA        #IMPLIED>
   <!ATTLIST intOption origin       CDATA        #IMPLIED>
   <!ATTLIST intOption description  CDATA        #IMPLIED>
   <!ATTLIST intOption toolTip      CDATA        #IMPLIED>
   <!ATTLIST intOption value        CDATA        #IMPLIED>
   <!ATTLIST intOption units        (None|Hz|s)  "None">
   <!ATTLIST intOption step         CDATA        "1">
   <!-- Minimum value (displayed value) -->
   <!ATTLIST intOption min          CDATA        #IMPLIED>
   <!-- Maximum value (displayed value) -->
   <!ATTLIST intOption max          CDATA        #IMPLIED>
   <!-- Offset to translate from displayed value to substitution value -->
   <!ATTLIST intOption offset       CDATA        "0">
   <!ATTLIST intOption indexedBy    CDATA        #IMPLIED>
   <!ATTLIST intOption derived      (false|true) "false">
   <!ATTLIST intOption derivedFrom  IDREF        #IMPLIED>
  
<!ELEMENT bitmaskOption EMPTY >
   <!ATTLIST bitmaskOption constant      (false|true) "false">
   <!ATTLIST bitmaskOption name          ID           #REQUIRED>
   <!ATTLIST bitmaskOption key           CDATA        #IMPLIED>
   <!ATTLIST bitmaskOption origin        CDATA        #IMPLIED>
   <!ATTLIST bitmaskOption description   CDATA        #IMPLIED>
   <!ATTLIST bitmaskOption toolTip       CDATA        #IMPLIED>
   <!ATTLIST bitmaskOption value         CDATA        #IMPLIED>
   <!ATTLIST bitmaskOption bitmask       CDATA        "0xFFFF">
   <!ATTLIST bitmaskOption bitList       CDATA        "">
   <!ATTLIST bitmaskOption indexedBy     CDATA        #IMPLIED>
   <!ATTLIST bitmaskOption derived       (false|true) "false">
   <!ATTLIST bitmaskOption derivedFrom   IDREF        #IMPLIED>
  
<!ELEMENT floatOption EMPTY >
   <!ATTLIST floatOption constant     (false|true) "false">
   <!ATTLIST floatOption name         ID           #REQUIRED>
   <!ATTLIST floatOption key          CDATA        #IMPLIED>
   <!ATTLIST floatOption origin       CDATA        #IMPLIED>
   <!ATTLIST floatOption description  CDATA        #IMPLIED>
   <!ATTLIST floatOption toolTip      CDATA        #IMPLIED>
   <!ATTLIST floatOption value        CDATA        #IMPLIED>
   <!ATTLIST floatOption units        (None|Hz|s)  "None">
   <!-- Minimum value (displayed value) -->
   <!ATTLIST floatOption min          CDATA        #IMPLIED>
   <!-- Maximum value (displayed value) -->
   <!ATTLIST floatOption max          CDATA        #IMPLIED>
   <!ATTLIST floatOption derived      (false|true) "false">
   <!ATTLIST floatOption derivedFrom  IDREF        #IMPLIED>
  
<!ELEMENT aliasOption EMPTY >
   <!-- alias Option 
   name 		Refers to another option within the same file and will be used as key and validated as a reference to an ID
   key  		Allows reference to an option (possibly) in another file while passing validation
   displayName	Allows the name of the model (visible in the GUI) to differ from the aliased option's name
   -->
   <!ATTLIST aliasOption name        IDREF        #IMPLIED>
   <!ATTLIST aliasOption key         CDATA        #IMPLIED>
   <!ATTLIST aliasOption displayName CDATA        #IMPLIED>
   <!ATTLIST aliasOption description CDATA        #IMPLIED>
   <!ATTLIST aliasOption toolTip     CDATA        #IMPLIED>
   <!ATTLIST aliasOption constant    (false|true) "true">
   <!ATTLIST aliasOption optional    (false|true) "false">

<!ELEMENT stringOption EMPTY >
   <!ATTLIST stringOption constant     (false|true) "false">
   <!ATTLIST stringOption name         ID           #REQUIRED>
   <!ATTLIST stringOption key          CDATA        #IMPLIED>
   <!ATTLIST stringOption origin       CDATA        #IMPLIED>
   <!ATTLIST stringOption description  CDATA        #IMPLIED>
   <!ATTLIST stringOption toolTip      CDATA        #IMPLIED>
   <!ATTLIST stringOption value        CDATA        #IMPLIED>
   <!ATTLIST stringOption indexedBy    CDATA        #IMPLIED>
   <!ATTLIST stringOption derived      (false|true) "false">
   <!ATTLIST stringOption derivedFrom  IDREF        #IMPLIED>
  
<!ELEMENT numericListOption EMPTY >
   <!ATTLIST numericListOption constant     (false|true) "false">
   <!ATTLIST numericListOption name         ID           #REQUIRED>
   <!ATTLIST numericListOption key          CDATA        #IMPLIED>
   <!ATTLIST numericListOption origin       CDATA        #IMPLIED>
   <!ATTLIST numericListOption description  CDATA        #IMPLIED>
   <!ATTLIST numericListOption toolTip      CDATA        #IMPLIED>
   <!ATTLIST numericListOption value        CDATA        #IMPLIED>
   <!ATTLIST numericListOption size         CDATA        #IMPLIED>
   <!ATTLIST numericListOption min          CDATA        #IMPLIED>
   <!ATTLIST numericListOption max          CDATA        #IMPLIED>
   <!ATTLIST numericListOption indexedBy    CDATA        #IMPLIED>
   <!ATTLIST numericListOption derived      (false|true) "false">
   <!ATTLIST numericListOption derivedFrom  IDREF        #IMPLIED>
  
<!ELEMENT pinListOption EMPTY >
   <!ATTLIST pinListOption constant     (false|true) "false">
   <!ATTLIST pinListOption name         ID           #REQUIRED>
   <!ATTLIST pinListOption key          CDATA        #IMPLIED>
   <!ATTLIST pinListOption origin       CDATA        #IMPLIED>
   <!ATTLIST pinListOption description  CDATA        #IMPLIED>
   <!ATTLIST pinListOption toolTip      CDATA        #IMPLIED>
   <!ATTLIST pinListOption value        CDATA        #IMPLIED>
   <!ATTLIST pinListOption size         CDATA        #IMPLIED>
   <!ATTLIST pinListOption indexedBy    CDATA        #IMPLIED>
   <!ATTLIST pinListOption derived      (false|true) "false">
   <!ATTLIST pinListOption derivedFrom  IDREF        #IMPLIED>
  
<!ELEMENT choiceOption (choice)* >
   <!ATTLIST choiceOption constant     (false|true) "false">
   <!ATTLIST choiceOption name         ID           #REQUIRED>
   <!ATTLIST choiceOption key          CDATA        #IMPLIED>
   <!ATTLIST choiceOption origin       CDATA        #IMPLIED>
   <!ATTLIST choiceOption description  CDATA        #IMPLIED>
   <!ATTLIST choiceOption toolTip      CDATA        #IMPLIED>
   <!ATTLIST choiceOption units        (None|Hz|Seconds)    "None">
   <!ATTLIST choiceOption indexedBy    CDATA        #IMPLIED>
   <!ATTLIST choiceOption derived      (false|true) "false">
   <!ATTLIST choiceOption derivedFrom  IDREF        #IMPLIED>
  
<!ELEMENT choice EMPTY >
   <!ATTLIST choice value        CDATA        #REQUIRED>
   <!ATTLIST choice name         CDATA        #REQUIRED>
   <!ATTLIST choice isDefault    (false|true) "false">

<!ELEMENT binaryOption (choice, choice) >
   <!ATTLIST binaryOption constant     (false|true) "false">
   <!ATTLIST binaryOption name         ID           #REQUIRED>
   <!ATTLIST binaryOption key          CDATA        #IMPLIED>
   <!ATTLIST binaryOption origin       CDATA        #IMPLIED>
   <!ATTLIST binaryOption description  CDATA        #IMPLIED>
   <!ATTLIST binaryOption toolTip      CDATA        #IMPLIED>
   <!ATTLIST binaryOption indexedBy    CDATA        #IMPLIED>
   <!ATTLIST binaryOption derived      (false|true) "false">
   <!ATTLIST binaryOption derivedFrom  IDREF        #IMPLIED>

<!ELEMENT irqOption EMPTY >
   <!ATTLIST irqOption constant     (false|true) "false">
   <!ATTLIST irqOption name         ID           #REQUIRED>
   <!ATTLIST irqOption key          CDATA        #IMPLIED>
   <!ATTLIST irqOption pattern      CDATA        #REQUIRED>
   <!ATTLIST irqOption classHandler CDATA        #REQUIRED>
   <!ATTLIST irqOption value        CDATA        #IMPLIED>
   <!ATTLIST irqOption origin       CDATA        #IMPLIED>
   <!ATTLIST irqOption description  CDATA        #IMPLIED>
   <!ATTLIST irqOption toolTip      CDATA        #IMPLIED>
   <!ATTLIST irqOption derived      (false|true) "false">
   <!ATTLIST irqOption derivedFrom  IDREF        #IMPLIED>

<!ELEMENT template (#PCDATA)>
   <!ATTLIST template namespace (info|usbdm|class|all)  "info" >
   <!ATTLIST template name 		CDATA  					"" >
   <!ATTLIST template dim  		CDATA  					"0" >

<!ELEMENT validate (param*) >
   <!ATTLIST validate class CDATA #REQUIRED>
   <!ATTLIST validate dim  		   CDATA        "0" >
   
<!ELEMENT param EMPTY >
   <!ATTLIST param type  (long|string) #REQUIRED>
   <!ATTLIST param value CDATA         #REQUIRED>

<!ELEMENT signals EMPTY >
   <!ATTLIST signals name CDATA "" >

<!-- List of actions to be applied to a project -->
<!ELEMENT projectActionList ((deleteResource|copy|constant)*) >
   <!ATTLIST projectActionList id          ID            #REQUIRED>
   <!ATTLIST projectActionList root        CDATA         #IMPLIED>
   <!ATTLIST projectActionList doOnceOnly  (true|false)  "true">
   
<!-- Exclude/include source file in Eclipse project -->
<!ELEMENT excludeSourceFile EMPTY >
   <!ATTLIST excludeSourceFile target  CDATA         #REQUIRED>
   <!ATTLIST excludeSourceFile excluded (true|false) "true" >

<!-- Exclude/include source folder in Eclipse project -->
<!ELEMENT excludeSourceFolder EMPTY >
   <!ATTLIST excludeSourceFolder target  CDATA         #REQUIRED>
   <!ATTLIST excludeSourceFolder excluded (true|false) "true" >

<!-- Remove file from Eclipse project -->
<!ELEMENT deleteResource EMPTY >
   <!ATTLIST deleteResource target  CDATA         #REQUIRED>

 <!ELEMENT createFolder EMPTY >
   <!ATTLIST createFolder target  CDATA #REQUIRED>
   <!ATTLIST createFolder type    (source|include|normal) "normal">

<!-- File to be copied to a project -->
<!ELEMENT copy EMPTY >
   <!ATTLIST copy source               CDATA #REQUIRED>
   <!ATTLIST copy target               CDATA #REQUIRED>
   <!ATTLIST copy type                 CDATA #IMPLIED>
   <!ATTLIST copy sourcePathType       (absolute|relative|unknown) #IMPLIED>
   <!ATTLIST copy macroReplace         (true|false) "true">
   <!ATTLIST copy overwrite            (true|false) "false">
   <!ATTLIST copy derived              (true|false) "false">
   
<!ELEMENT constant EMPTY >
   <!-- constant 
   key       Allows specification of a explicit key rather than based upon the name.
   name      In the absence of a key it is used to create a key tied to the current peripheral/file. 
             Used as visible name in GUI (model)
             Supports validation as an ID.
   weak	     If true indicates the constant may already exist and this constant is discarded
   overwrite Replaces any existing constant of the same key
   -->
   <!ATTLIST constant name         ID           #IMPLIED>
   <!ATTLIST constant key          CDATA        #IMPLIED>
   <!ATTLIST constant value        CDATA        #REQUIRED>
   <!ATTLIST constant type         (boolean|int|string)  "string" >
   <!ATTLIST constant weak         (true|false)          "false">
   <!ATTLIST constant replace      (true|false)          "false">
   <!ATTLIST constant derived      (true|false)          "false">
   
<!ELEMENT divider EMPTY >

=== EgorKin/usbdm-eclipse-makefiles-build/PackageFiles/Stationery/Packages/180.ARM_Peripherals/Hardware/peripherals/llwu_pe4_filt2_rst_base.xml
<?xml version="1.0" encoding="UTF-8"
?>
<!DOCTYPE peripheralPage SYSTEM "_menu.dtd" >
<!-- llwu_pe4_filt2_rst_base.xml -->

<fragment xmlns:xi="http://www.w3.org/2001/XInclude">

   <xi:include href="llwu_pe4_filt2_base.xml"/>

   <binaryOption 
      name="llwu_rst_llrste" 
      description="Low-Leakage Mode RESET Enable"
      toolTip="This bit must be set to allow the device to be reset while in a low-leakage power mode.\n
         On devices where Reset is not a dedicated pin, the RESET pin must also be enabled\n
         in the explicit port mux control." >
      <choice name="RESET pin not enabled as a LLWU mode exit source"  value="0" />
      <choice name="RESET pin enabled as a LLWU mode exit source"      value="1" isDefault="true" />
   </binaryOption>      
   
   <binaryOption 
      name="llwu_rst_rstfilt" 
      description="Digital Filter On RESET Pin"
      toolTip="Enables the digital filter for the RESET pin during LLS, VLLS3, VLLS2, or VLLS1 modes." >
      <choice name="Filter not enabled"  value="0" isDefault="true" />
      <choice name="Filter enabled"      value="1" />
   </binaryOption>      
   
   <template><![CDATA[
      \t// LLWU Reset Enable register
      \tstatic constexpr uint8_t rst =
      \t   LLWU_RST_LLRSTE($(llwu_rst_llrste)) |  // Low-Leakage Mode RESET Enable
      \t   LLWU_RST_RSTFILT($(llwu_rst_rstfilt));  // Digital Filter On RESET Pin\n\n
   ]]></template>

         
</fragment>

=== EgorKin/usbdm-eclipse-makefiles-build/PackageFiles/Stationery/Packages/180.ARM_Peripherals/Hardware/peripherals/can1_s32k14x.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE peripheralPage SYSTEM "_menu.dtd" >
<!-- can1_s32k14x.xml -->

<peripheralPage xmlns:xi="http://www.w3.org/2001/XInclude" name="_instance" description="FlexCAN">

   <template><![CDATA[
      \t//! Base value for PCR (excluding MUX value)
      \tstatic constexpr uint32_t defaultPcrValue  = 0;\n\n
   ]]></template>
   
   <xi:include href="_mapPinsOption.xml"/>
   
   <intOption name="NumberOfMessageBuffers" 
      description="Number of message buffers available"
      toolTip="This value is determined by the hardware"
      constant="true" 
      value="16" />

   <intOption name="NumberOfMessageFilters" 
      description="Number of message buffers available"
      toolTip="This value is determined by the hardware"
      constant="true" 
      value="40" />

   <template><![CDATA[
       \t//! Number of Message Buffers\n
       \tstatic constexpr unsigned NumberOfMessageBuffers =  $(NumberOfMessageBuffers);\n\n
       \t//! Number of Message Filters\n
       \tstatic constexpr unsigned NumberOfMessageFilters =  $(NumberOfMessageFilters);\n\n
   ]]></template>

   <!--
   Patterns for pattern and classHandler 
     -  %i replaced with peripheral instance e.g. FTM1 => 1, PTA => A
     -  %b replaced with peripheral base name e.g. FTM1 => = FTM
     -  %c replaced with peripheral C++ base class name e.g. FTM1 => = Ftm
     -  _IRQHandler is appended to the pattern (only)
   -->
   <irqOption name="oredIrqHandlingMethod"  
      description="ORed Interrupt handlers"
      toolTip="This selection allow the interrupt handler for this peripheral to be installed using several different methods"
      pattern="^%b%i_ORed$" 
      classHandler="%c%i::irqHandler" />

   <irqOption name="errorIrqHandlingMethod"  
      description="Error Interrupt handlers"
      toolTip="This selection allow the interrupt handler for this peripheral to be installed using several different methods"
      pattern="^%b%i_Error$" 
      classHandler="%c%i::errorIrqHandler" />

   <irqOption name="wakeupIrqHandlingMethod"  
      description="Wakeup Interrupt handlers"
      toolTip="This selection allow the interrupt handler for this peripheral to be installed using several different methods"
      pattern="^%b%i_WakeUp$" 
      classHandler="%c%i::wakeupIrqHandler" />

   <irqOption name="messagebufferIrqHandlingMethod"  
      description="Message Buffer Interrupt handlers"
      toolTip="This selection allow the interrupt handler for this peripheral to be installed using several different methods"
      pattern="^%b%i_MessageBuffer.*$" 
      classHandler="%c%i::messageBufferIrqHandler" />

   <signals/>
   
   
   <!-- Template is added to class within pin_mapping.h -->
   <template><![CDATA[
       \t//! Class based callback handler has been installed in vector table\n
       \tstatic constexpr bool irqHandlerInstalled = $(messagebufferIrqHandlingMethod);\n\n
       
       \tstatic constexpr unsigned OredIrqNumIndex                 = 0;
       \tstatic constexpr unsigned ErrorIrqNumIndex                = 1;
       \tstatic constexpr unsigned WakeupIrqNumIndex               = -1;
       \tstatic constexpr unsigned MessageBuffer_0_15_IrqNumIndex  = 2;
       \tstatic constexpr unsigned MessageBuffer_16_32_IrqNumIndex = 2;\n\n
   ]]></template>
       
   <intOption name="irqLevel" 
      description="IRQ Level in NVIC [0-15]"
      toolTip="Sets the priority level used to configure the NVIC\n
               Lower numbers represent higher priorities"
      value="8" min="0" max="15" 
   />
   
   <template><![CDATA[
      \t/**
      \t * Get Controller Host Interface input clock frequency
      \t *
      \t * @return Input clock frequency as a uint32_t in Hz
      \t */
      \tstatic uint32_t getChiClockFrequency() {
      \t   return SystemCoreClock;
      \t}\n\n
   ]]></template>

   <template><![CDATA[
      \t/**
      \t * Get Protocol Engine input clock frequency
      \t *
      \t * @return Input clock frequency as a uint32_t in Hz
      \t */
      \tstatic uint32_t getPeClockFrequency() {
      \t   if (can().CTRL1 & CAN_CTRL1_CLKSRC_MASK) {
      \t      return ScgInfo::getSoscDiv2Frequency();
      \t   }
      \t   else {
      \t      return SystemCoreClock;
      \t   }
      \t}\n\n
   ]]></template>

   <template><![CDATA[
       \t//! Default IRQ level\n
       \tstatic constexpr uint32_t irqLevel =  $(irqLevel);\n\n
   ]]></template>

   <xi:include href="_clockOption.xml"/>
      
   <projectActionList id = "can_files" >
      <copy source="Project_Headers/can.h"                    target="Project_Headers/can.h"                    overwrite="true"  derived="true" />
   </projectActionList>
   
</peripheralPage>

=== EgorKin/usbdm-eclipse-makefiles-build/PackageFiles/Stationery/Packages/180.ARM_Peripherals/Hardware/peripherals/dmamux0_32ch_trig_mk66f18.xml
<?xml version="1.0" encoding="UTF-8"
?>
<!DOCTYPE peripheralPage SYSTEM "_menu.dtd" >
<!-- dmamux0_4ch_trig_mk20d5.xml -->

<peripheralPage xmlns:xi="http://www.w3.org/2001/XInclude" name="_instance" description="Flash Memory Module">

   <aliasOption key="/DMA0/NumChannels" displayName="NumChannels" constant="true" />

   <choiceOption name="dma_chcfg0"
      description="Mapping of DMA source (slot) to DMA channel" >
      <choice value="0"  name="Disabled" />
      <choice value="1"  name="TSI0" />
      <choice value="2"  name="UART0 Receive" />
      <choice value="3"  name="UART0 Transmit" />
      <choice value="4"  name="UART1 Receive" />
      <choice value="5"  name="UART1 Transmit" />
      <choice value="6"  name="UART2 Receive" />
      <choice value="7"  name="UART2 Transmit" />
      <choice value="8"  name="UART3 Receive" />
      <choice value="9"  name="UART3 Transmit" />
      <choice value="10" name="UART4 Tx Rx" />
      <choice value="12" name="I2S0 Receive" />
      <choice value="13" name="I2S0 Transmit" />
      <choice value="14" name="SPI0 Receive" />
      <choice value="15" name="SPI0 Transmit" />
      <choice value="16" name="SPI1 Receive" />
      <choice value="17" name="SPI1 Transmit" />
      <choice value="22" name="I2C0 I2C3" />
      <choice value="22" name="I2C1 I2C2" />
      <choice value="20" name="FTM0 Channel 0" />
      <choice value="21" name="FTM0 Channel 1" />
      <choice value="22" name="FTM0 Channel 2" />
      <choice value="23" name="FTM0 Channel 3" />
      <choice value="24" name="FTM0 Channel 4" />
      <choice value="25" name="FTM0 Channel 5" />
      <choice value="26" name="FTM0 Channel 6" />
      <choice value="27" name="FTM0 Channel 7" />
      <choice value="28" name="FTM1/TPM1 Channel 0" />
      <choice value="29" name="FTM1/TPM1 Channel 1" />
      <choice value="30" name="FTM2/TPM2 Channel 0" />
      <choice value="31" name="FTM2/TPM2 Channel 1" />
      <choice value="32" name="FTM3 Channel 0" />
      <choice value="33" name="FTM3 Channel 1" />
      <choice value="34" name="FTM3 Channel 2" />
      <choice value="35" name="FTM3 Channel 3" />
      <choice value="36" name="FTM3 Channel 4" />
      <choice value="37" name="FTM3 Channel 5" />
      <choice value="38" name="FTM3 Channel 6/SPI2 Rx" />
      <choice value="39" name="FTM3 Channel 7/SPI2 Tx" />
      <choice value="40" name="ADC0" />
      <choice value="42" name="CMP0" />
      <choice value="43" name="CMP1" />
      <choice value="44" name="CMP2/CMP3" />
      <choice value="45" name="DAC0" />
      <choice value="46" name="DAC1" />
      <choice value="47" name="CMT" />
      <choice value="48" name="PDB" />
      <choice value="49" name="Port A" />
      <choice value="50" name="Port B" />
      <choice value="51" name="Port C" />
      <choice value="52" name="Port D" />
      <choice value="54" name="IEEE 1588 Timer 0" />
      <choice value="55" name="IEEE 1588 Timer 1/TPM1 Overflow" />
      <choice value="56" name="IEEE 1588 Timer 2/TPM2 Overflow" />
      <choice value="58" name="LPUART0 Receive" />
      <choice value="59" name="LPUART0 Transmit" />
      <choice value="60" name="Always enabled 0" />
      <choice value="61" name="Always enabled 1" />
      <choice value="62" name="Always enabled 2" />
      <choice value="63" name="Always enabled 3" />
   </choiceOption>

   <choiceOption name="dma_chcfg1"  derivedFrom="dma_chcfg0"/>
   <choiceOption name="dma_chcfg2"  derivedFrom="dma_chcfg0"/>
   <choiceOption name="dma_chcfg3"  derivedFrom="dma_chcfg0"/>
   <choiceOption name="dma_chcfg4"  derivedFrom="dma_chcfg0"/>
   <choiceOption name="dma_chcfg5"  derivedFrom="dma_chcfg0"/>
   <choiceOption name="dma_chcfg6"  derivedFrom="dma_chcfg0"/>
   <choiceOption name="dma_chcfg7"  derivedFrom="dma_chcfg0"/>
   <choiceOption name="dma_chcfg8"  derivedFrom="dma_chcfg0"/>
   <choiceOption name="dma_chcfg9"  derivedFrom="dma_chcfg0"/>
   <choiceOption name="dma_chcfg10" derivedFrom="dma_chcfg0"/>
   <choiceOption name="dma_chcfg11" derivedFrom="dma_chcfg0"/>
   <choiceOption name="dma_chcfg12" derivedFrom="dma_chcfg0"/>
   <choiceOption name="dma_chcfg13" derivedFrom="dma_chcfg0"/>
   <choiceOption name="dma_chcfg14" derivedFrom="dma_chcfg0"/>
   <choiceOption name="dma_chcfg15" derivedFrom="dma_chcfg0"/>
   <choiceOption name="dma_chcfg16" derivedFrom="dma_chcfg0"/>
   <choiceOption name="dma_chcfg17" derivedFrom="dma_chcfg16"/>
   <choiceOption name="dma_chcfg18" derivedFrom="dma_chcfg16"/>
   <choiceOption name="dma_chcfg19" derivedFrom="dma_chcfg16"/>
   <choiceOption name="dma_chcfg20" derivedFrom="dma_chcfg16"/>
   <choiceOption name="dma_chcfg21" derivedFrom="dma_chcfg16"/>
   <choiceOption name="dma_chcfg22" derivedFrom="dma_chcfg16"/>
   <choiceOption name="dma_chcfg23" derivedFrom="dma_chcfg16"/>
   <choiceOption name="dma_chcfg24" derivedFrom="dma_chcfg16"/>
   <choiceOption name="dma_chcfg25" derivedFrom="dma_chcfg16"/>
   <choiceOption name="dma_chcfg26" derivedFrom="dma_chcfg16"/>
   <choiceOption name="dma_chcfg27" derivedFrom="dma_chcfg16"/>
   <choiceOption name="dma_chcfg28" derivedFrom="dma_chcfg16"/>
   <choiceOption name="dma_chcfg29" derivedFrom="dma_chcfg16"/>
   <choiceOption name="dma_chcfg30" derivedFrom="dma_chcfg16"/>
   <choiceOption name="dma_chcfg31" derivedFrom="dma_chcfg16"/>
   
   <template namespace="usbdm"><![CDATA[
      \t/** 
      \t * DMA channel numbers 
      \t */
      \tenum DmaSlot {
      \t // Channels 0-15 only
      \t   DmaSlot_Disabled                      =  0,
      \t   DmaSlot_UART0_Receive                 =  2,
      \t   DmaSlot_UART0_Transmit                =  3,
      \t   DmaSlot_UART1_Receive                 =  4,
      \t   DmaSlot_UART1_Transmit                =  5,
      \t   DmaSlot_UART2_Receive                 =  6,
      \t   DmaSlot_UART2_Transmit                =  7,
      \t   DmaSlot_UART3_Receive                 =  8,
      \t   DmaSlot_UART3_Transmit                =  9,
      \t   DmaSlot_UART4_Tx_Rx                   = 10,
      \t   DmaSlot_I2S0_Receive                  = 12,
      \t   DmaSlot_I2S0_Transmit                 = 13,
      \t   DmaSlot_SPI0_Receive                  = 14,
      \t   DmaSlot_SPI0_Transmit                 = 15,
      \t   DmaSlot_SPI1_Receive                  = 16,
      \t   DmaSlot_SPI1_Transmit                 = 17,
      \t   DmaSlot_I2C0_I2C3                     = 18,
      \t   DmaSlot_I2C1_I2C2                     = 19,
      \t   DmaSlot_FTM0_Ch0                      = 20,
      \t   DmaSlot_FTM0_Ch1                      = 21,
      \t   DmaSlot_FTM0_Ch2                      = 22,
      \t   DmaSlot_FTM0_Ch3                      = 23,
      \t   DmaSlot_FTM0_Ch4                      = 24,
      \t   DmaSlot_FTM0_Ch5                      = 25,
      \t   DmaSlot_FTM0_Ch6                      = 26,
      \t   DmaSlot_FTM0_Ch7                      = 27,
      \t   DmaSlot_FTM1_TPM1_Ch0                 = 28,
      \t   DmaSlot_FTM1_TPM1_Ch1                 = 29,
      \t   DmaSlot_FTM2_TPM2_Ch0                 = 30,
      \t   DmaSlot_FTM2_TPM2_Ch1                 = 31,
      \t   DmaSlot_FTM3_Ch0                      = 32,
      \t   DmaSlot_FTM3_Ch1                      = 33,
      \t   DmaSlot_FTM3_Ch2                      = 34,
      \t   DmaSlot_FTM3_Ch3                      = 35,
      \t   DmaSlot_FTM3_Ch4                      = 36,
      \t   DmaSlot_FTM3_Ch5                      = 37,
      \t   DmaSlot_FTM3_Ch6_SPI2_Rx              = 38,
      \t   DmaSlot_FTM3_Ch7_SPI2_Tx              = 39,
      \t   DmaSlot_ADC0                          = 40,
      \t   DmaSlot_CMP0                          = 42,
      \t   DmaSlot_CMP1                          = 43,
      \t   DmaSlot_CMP2_CMP3                     = 44,
      \t   DmaSlot_DAC0                          = 45,
      \t   DmaSlot_DAC1                          = 46,
      \t   DmaSlot_CMT                           = 47,
      \t   DmaSlot_PDB                           = 48,
      \t   DmaSlot_PortA                         = 49,
      \t   DmaSlot_PortB                         = 50,
      \t   DmaSlot_PortC                         = 51,
      \t   DmaSlot_PortD                         = 52,
      \t   DmaSlot_PortE                         = 53,
      \t   DmaSlot_IEEE1588_Timer0               = 54,
      \t   DmaSlot_IEEE1588_Timer1_TPM1_Overflow = 55,
      \t   DmaSlot_IEEE1588_Timer2_TPM2_Overflow = 56,
      \t   DmaSlot_LPUART0_Receive               = 58,
      \t   DmaSlot_LPUART0_Transmit              = 59,
      \t   DmaSlot_AlwaysEnabled0                = 60,
      \t   DmaSlot_AlwaysEnabled1                = 61,
      \t   DmaSlot_AlwaysEnabled2                = 62,
      \t   DmaSlot_AlwaysEnabled3                = 63,
      \t};\n\n
   ]]></template>
</peripheralPage>
