=== EgorKin/usbdm-eclipse-makefiles-build/PackageFiles/Stationery/Packages/180.ARM_Peripherals/Hardware/peripherals/_menu.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ENTITY % gui_items        "(xi:include|category|indexedCategory|constant|floatOption|intOption|bitmaskOption|choiceOption|binaryOption|irqOption|stringOption|numericListOption|pinListOption|aliasOption|signals)" >
<!ENTITY % structure_items  "(xi:include|section|list)" >
<!ENTITY % control_items    "(xi:include|template|validate|projectActionList)" >

<!-- Include another file -->
<!ELEMENT xi:include EMPTY>
   <!ATTLIST xi:include href      CDATA        #REQUIRED>

<!-- Root fileElement -->
<!ELEMENT peripheralPage ((%structure_items;|%gui_items;|%control_items;)*) >
   <!ATTLIST peripheralPage xmlns:xi     CDATA        #IMPLIED>
   <!ATTLIST peripheralPage name         CDATA        #REQUIRED>
   <!ATTLIST peripheralPage description  CDATA        #REQUIRED>
   <!ATTLIST peripheralPage toolTip      CDATA        #IMPLIED>

<!ELEMENT fragment ANY >
   <!ATTLIST fragment xmlns:xi CDATA #IMPLIED>

<!ELEMENT list (((%structure_items;),(%control_items;)*)|(%gui_items;|%control_items;)*) >
   <!ATTLIST list name         CDATA        #IMPLIED>
   <!ATTLIST list description  CDATA        #IMPLIED>

<!ELEMENT section (((%structure_items;),(%control_items;)*)|(%gui_items;|%control_items;)*) >
   <!ATTLIST section name         CDATA        #IMPLIED>

<!ELEMENT indexedCategory ((%gui_items;)*) >
   <!ATTLIST indexedCategory xmlns:xi     CDATA        #IMPLIED>
   <!ATTLIST indexedCategory name         ID           #REQUIRED>
   <!ATTLIST indexedCategory description  CDATA        #REQUIRED>
   <!ATTLIST indexedCategory toolTip      CDATA        #IMPLIED>
   <!ATTLIST indexedCategory dim          CDATA        "0" >
   <!ATTLIST indexedCategory value        CDATA        #IMPLIED>
   <!ATTLIST indexedCategory constant     (false|true) "false">

<!ELEMENT category ((%gui_items;|template)*) >
   <!ATTLIST category xmlns:xi     CDATA        #IMPLIED>
   <!ATTLIST category name         CDATA        #REQUIRED>
   <!ATTLIST category description  CDATA        #REQUIRED>
   <!ATTLIST category toolTip      CDATA        #IMPLIED>

<!ELEMENT intOption EMPTY >
   <!ATTLIST intOption constant     (false|true) "false">
   <!ATTLIST intOption name         ID           #REQUIRED>
   <!ATTLIST intOption key          CDATA        #IMPLIED>
   <!ATTLIST intOption origin       CDATA        #IMPLIED>
   <!ATTLIST intOption description  CDATA        #IMPLIED>
   <!ATTLIST intOption toolTip      CDATA        #IMPLIED>
   <!ATTLIST intOption value        CDATA        #IMPLIED>
   <!ATTLIST intOption units        (None|Hz|s)  "None">
   <!ATTLIST intOption step         CDATA        "1">
   <!-- Minimum value (displayed value) -->
   <!ATTLIST intOption min          CDATA        #IMPLIED>
   <!-- Maximum value (displayed value) -->
   <!ATTLIST intOption max          CDATA        #IMPLIED>
   <!-- Offset to translate from displayed value to substitution value -->
   <!ATTLIST intOption offset       CDATA        "0">
   <!ATTLIST intOption indexedBy    CDATA        #IMPLIED>
   <!ATTLIST intOption derived      (false|true) "false">
   <!ATTLIST intOption derivedFrom  IDREF        #IMPLIED>
  
<!ELEMENT bitmaskOption EMPTY >
   <!ATTLIST bitmaskOption constant      (false|true) "false">
   <!ATTLIST bitmaskOption name          ID           #REQUIRED>
   <!ATTLIST bitmaskOption key           CDATA        #IMPLIED>
   <!ATTLIST bitmaskOption origin        CDATA        #IMPLIED>
   <!ATTLIST bitmaskOption description   CDATA        #IMPLIED>
   <!ATTLIST bitmaskOption toolTip       CDATA        #IMPLIED>
   <!ATTLIST bitmaskOption value         CDATA        #IMPLIED>
   <!ATTLIST bitmaskOption bitmask       CDATA        "0xFFFF">
   <!ATTLIST bitmaskOption bitList       CDATA        "">
   <!ATTLIST bitmaskOption indexedBy     CDATA        #IMPLIED>
   <!ATTLIST bitmaskOption derived       (false|true) "false">
   <!ATTLIST bitmaskOption derivedFrom   IDREF        #IMPLIED>
  
<!ELEMENT floatOption EMPTY >
   <!ATTLIST floatOption constant     (false|true) "false">
   <!ATTLIST floatOption name         ID           #REQUIRED>
   <!ATTLIST floatOption key          CDATA        #IMPLIED>
   <!ATTLIST floatOption origin       CDATA        #IMPLIED>
   <!ATTLIST floatOption description  CDATA        #IMPLIED>
   <!ATTLIST floatOption toolTip      CDATA        #IMPLIED>
   <!ATTLIST floatOption value        CDATA        #IMPLIED>
   <!ATTLIST floatOption units        (None|Hz|s)  "None">
   <!-- Minimum value (displayed value) -->
   <!ATTLIST floatOption min          CDATA        #IMPLIED>
   <!-- Maximum value (displayed value) -->
   <!ATTLIST floatOption max          CDATA        #IMPLIED>
   <!ATTLIST floatOption derived      (false|true) "false">
   <!ATTLIST floatOption derivedFrom  IDREF        #IMPLIED>
  
<!ELEMENT aliasOption EMPTY >
   <!-- alias Option 
   name 		Refers to another option within the same file and will be used as key and validated as a reference to an ID
   key  		Allows reference to an option (possibly) in another file while passing validation
   displayName	Allows the name of the model (visible in the GUI) to differ from the aliased option's name
   -->
   <!ATTLIST aliasOption name        IDREF        #IMPLIED>
   <!ATTLIST aliasOption key         CDATA        #IMPLIED>
   <!ATTLIST aliasOption displayName CDATA        #IMPLIED>
   <!ATTLIST aliasOption description CDATA        #IMPLIED>
   <!ATTLIST aliasOption toolTip     CDATA        #IMPLIED>
   <!ATTLIST aliasOption constant    (false|true) "true">
   <!ATTLIST aliasOption optional    (false|true) "false">

<!ELEMENT stringOption EMPTY >
   <!ATTLIST stringOption constant     (false|true) "false">
   <!ATTLIST stringOption name         ID           #REQUIRED>
   <!ATTLIST stringOption key          CDATA        #IMPLIED>
   <!ATTLIST stringOption origin       CDATA        #IMPLIED>
   <!ATTLIST stringOption description  CDATA        #IMPLIED>
   <!ATTLIST stringOption toolTip      CDATA        #IMPLIED>
   <!ATTLIST stringOption value        CDATA        #IMPLIED>
   <!ATTLIST stringOption indexedBy    CDATA        #IMPLIED>
   <!ATTLIST stringOption derived      (false|true) "false">
   <!ATTLIST stringOption derivedFrom  IDREF        #IMPLIED>
  
<!ELEMENT numericListOption EMPTY >
   <!ATTLIST numericListOption constant     (false|true) "false">
   <!ATTLIST numericListOption name         ID           #REQUIRED>
   <!ATTLIST numericListOption key          CDATA        #IMPLIED>
   <!ATTLIST numericListOption origin       CDATA        #IMPLIED>
   <!ATTLIST numericListOption description  CDATA        #IMPLIED>
   <!ATTLIST numericListOption toolTip      CDATA        #IMPLIED>
   <!ATTLIST numericListOption value        CDATA        #IMPLIED>
   <!ATTLIST numericListOption size         CDATA        #IMPLIED>
   <!ATTLIST numericListOption min          CDATA        #IMPLIED>
   <!ATTLIST numericListOption max          CDATA        #IMPLIED>
   <!ATTLIST numericListOption indexedBy    CDATA        #IMPLIED>
   <!ATTLIST numericListOption derived      (false|true) "false">
   <!ATTLIST numericListOption derivedFrom  IDREF        #IMPLIED>
  
<!ELEMENT pinListOption EMPTY >
   <!ATTLIST pinListOption constant     (false|true) "false">
   <!ATTLIST pinListOption name         ID           #REQUIRED>
   <!ATTLIST pinListOption key          CDATA        #IMPLIED>
   <!ATTLIST pinListOption origin       CDATA        #IMPLIED>
   <!ATTLIST pinListOption description  CDATA        #IMPLIED>
   <!ATTLIST pinListOption toolTip      CDATA        #IMPLIED>
   <!ATTLIST pinListOption value        CDATA        #IMPLIED>
   <!ATTLIST pinListOption size         CDATA        #IMPLIED>
   <!ATTLIST pinListOption indexedBy    CDATA        #IMPLIED>
   <!ATTLIST pinListOption derived      (false|true) "false">
   <!ATTLIST pinListOption derivedFrom  IDREF        #IMPLIED>
  
<!ELEMENT choiceOption (choice)* >
   <!ATTLIST choiceOption constant     (false|true) "false">
   <!ATTLIST choiceOption name         ID           #REQUIRED>
   <!ATTLIST choiceOption key          CDATA        #IMPLIED>
   <!ATTLIST choiceOption origin       CDATA        #IMPLIED>
   <!ATTLIST choiceOption description  CDATA        #IMPLIED>
   <!ATTLIST choiceOption toolTip      CDATA        #IMPLIED>
   <!ATTLIST choiceOption units        (None|Hz|Seconds)    "None">
   <!ATTLIST choiceOption indexedBy    CDATA        #IMPLIED>
   <!ATTLIST choiceOption derived      (false|true) "false">
   <!ATTLIST choiceOption derivedFrom  IDREF        #IMPLIED>
  
<!ELEMENT choice EMPTY >
   <!ATTLIST choice value        CDATA        #REQUIRED>
   <!ATTLIST choice name         CDATA        #REQUIRED>
   <!ATTLIST choice isDefault    (false|true) "false">

<!ELEMENT binaryOption (choice, choice) >
   <!ATTLIST binaryOption constant     (false|true) "false">
   <!ATTLIST binaryOption name         ID           #REQUIRED>
   <!ATTLIST binaryOption key          CDATA        #IMPLIED>
   <!ATTLIST binaryOption origin       CDATA        #IMPLIED>
   <!ATTLIST binaryOption description  CDATA        #IMPLIED>
   <!ATTLIST binaryOption toolTip      CDATA        #IMPLIED>
   <!ATTLIST binaryOption indexedBy    CDATA        #IMPLIED>
   <!ATTLIST binaryOption derived      (false|true) "false">
   <!ATTLIST binaryOption derivedFrom  IDREF        #IMPLIED>

<!ELEMENT irqOption EMPTY >
   <!ATTLIST irqOption constant     (false|true) "false">
   <!ATTLIST irqOption name         ID           #REQUIRED>
   <!ATTLIST irqOption key          CDATA        #IMPLIED>
   <!ATTLIST irqOption pattern      CDATA        #REQUIRED>
   <!ATTLIST irqOption classHandler CDATA        #REQUIRED>
   <!ATTLIST irqOption value        CDATA        #IMPLIED>
   <!ATTLIST irqOption origin       CDATA        #IMPLIED>
   <!ATTLIST irqOption description  CDATA        #IMPLIED>
   <!ATTLIST irqOption toolTip      CDATA        #IMPLIED>
   <!ATTLIST irqOption derived      (false|true) "false">
   <!ATTLIST irqOption derivedFrom  IDREF        #IMPLIED>

<!ELEMENT template (#PCDATA)>
   <!ATTLIST template namespace (info|usbdm|class|all)  "info" >
   <!ATTLIST template name 		CDATA  					"" >
   <!ATTLIST template dim  		CDATA  					"0" >

<!ELEMENT validate (param*) >
   <!ATTLIST validate class CDATA #REQUIRED>
   <!ATTLIST validate dim  		   CDATA        "0" >
   
<!ELEMENT param EMPTY >
   <!ATTLIST param type  (long|string) #REQUIRED>
   <!ATTLIST param value CDATA         #REQUIRED>

<!ELEMENT signals EMPTY >
   <!ATTLIST signals name CDATA "" >

<!-- List of actions to be applied to a project -->
<!ELEMENT projectActionList ((deleteResource|copy|constant)*) >
   <!ATTLIST projectActionList id          ID            #REQUIRED>
   <!ATTLIST projectActionList root        CDATA         #IMPLIED>
   <!ATTLIST projectActionList doOnceOnly  (true|false)  "true">
   
<!-- Exclude/include source file in Eclipse project -->
<!ELEMENT excludeSourceFile EMPTY >
   <!ATTLIST excludeSourceFile target  CDATA         #REQUIRED>
   <!ATTLIST excludeSourceFile excluded (true|false) "true" >

<!-- Exclude/include source folder in Eclipse project -->
<!ELEMENT excludeSourceFolder EMPTY >
   <!ATTLIST excludeSourceFolder target  CDATA         #REQUIRED>
   <!ATTLIST excludeSourceFolder excluded (true|false) "true" >

<!-- Remove file from Eclipse project -->
<!ELEMENT deleteResource EMPTY >
   <!ATTLIST deleteResource target  CDATA         #REQUIRED>

 <!ELEMENT createFolder EMPTY >
   <!ATTLIST createFolder target  CDATA #REQUIRED>
   <!ATTLIST createFolder type    (source|include|normal) "normal">

<!-- File to be copied to a project -->
<!ELEMENT copy EMPTY >
   <!ATTLIST copy source               CDATA #REQUIRED>
   <!ATTLIST copy target               CDATA #REQUIRED>
   <!ATTLIST copy type                 CDATA #IMPLIED>
   <!ATTLIST copy sourcePathType       (absolute|relative|unknown) #IMPLIED>
   <!ATTLIST copy macroReplace         (true|false) "true">
   <!ATTLIST copy overwrite            (true|false) "false">
   <!ATTLIST copy derived              (true|false) "false">
   
<!ELEMENT constant EMPTY >
   <!-- constant 
   key       Allows specification of a explicit key rather than based upon the name.
   name      In the absence of a key it is used to create a key tied to the current peripheral/file. 
             Used as visible name in GUI (model)
             Supports validation as an ID.
   weak	     If true indicates the constant may already exist and this constant is discarded
   overwrite Replaces any existing constant of the same key
   -->
   <!ATTLIST constant name         ID           #IMPLIED>
   <!ATTLIST constant key          CDATA        #IMPLIED>
   <!ATTLIST constant value        CDATA        #REQUIRED>
   <!ATTLIST constant type         (boolean|int|string)  "string" >
   <!ATTLIST constant weak         (true|false)          "false">
   <!ATTLIST constant replace      (true|false)          "false">
   <!ATTLIST constant derived      (true|false)          "false">
   
<!ELEMENT divider EMPTY >

=== EgorKin/usbdm-eclipse-makefiles-build/PackageFiles/Stationery/Packages/180.ARM_Peripherals/Hardware/peripherals/dmamux0_16ch_trig_mk22fa12.xml
<?xml version="1.0" encoding="UTF-8"
?>
<!DOCTYPE peripheralPage SYSTEM "_menu.dtd" >
<!-- dmamux0_16ch_trig_mk22f51212.xml -->

<peripheralPage xmlns:xi="http://www.w3.org/2001/XInclude" name="_instance" description="Flash Memory Module">

   <aliasOption key="/DMA0/NumChannels" displayName="NumChannels" constant="true" />

   <choiceOption name="dma_chcfg0"
      description="Mapping of DMA source (slot) to DMA channel" >
      <choice value="0"  name="Disabled" />
      <choice value="2"  name="UART0 Receive" />
      <choice value="3"  name="UART0 Transmit" />
      <choice value="4"  name="UART1 Receive" />
      <choice value="5"  name="UART1 Transmit" />
      <choice value="6"  name="UART2 Receive" />
      <choice value="7"  name="UART2 Transmit" />
      <choice value="12" name="I2S0 Receive" />
      <choice value="13" name="I2S0 Transmit" />
      <choice value="14" name="SPI0 Receive" />
      <choice value="15" name="SPI0 Transmit" />
      <choice value="18" name="I2C0" />
      <choice value="19" name="I2C1 I2C2" />
      <choice value="20" name="FTM0 Channel 0" />
      <choice value="21" name="FTM0 Channel 1" />
      <choice value="22" name="FTM0 Channel 2" />
      <choice value="23" name="FTM0 Channel 3" />
      <choice value="24" name="FTM0 Channel 4" />
      <choice value="25" name="FTM0 Channel 5" />
      <choice value="26" name="FTM0 Channel 6" />
      <choice value="27" name="FTM0 Channel 7" />
      <choice value="28" name="FTM1 Channel 0" />
      <choice value="29" name="FTM1 Channel 1" />
      <choice value="30" name="FTM2 Channel 0" />
      <choice value="31" name="FTM2 Channel 1" />
      <choice value="32" name="FTM3 Channel 0" />
      <choice value="33" name="FTM3 Channel 1" />
      <choice value="34" name="FTM3 Channel 2" />
      <choice value="35" name="FTM3 Channel 3" />
      <choice value="36" name="FTM3 Channel 4" />
      <choice value="37" name="FTM3 Channel 5" />
      <choice value="38" name="FTM3 Channel 6" />
      <choice value="39" name="FTM3 Channel 7" />
      <choice value="40" name="ADC0" />
      <choice value="41" name="ADC1" />
      <choice value="42" name="CMP0" />
      <choice value="43" name="CMP1" />
      <choice value="44" name="CMP2" />
      <choice value="45" name="DAC0" />
      <choice value="47" name="CMT" />
      <choice value="48" name="PDB" />
      <choice value="49" name="Port A" />
      <choice value="50" name="Port B" />
      <choice value="51" name="Port C" />
      <choice value="52" name="Port D" />
      <choice value="53" name="Port E" />
      <choice value="54" name="Always enabled 54" />
      <choice value="55" name="Always enabled 55" />
      <choice value="56" name="Always enabled 56" />
      <choice value="57" name="Always enabled 57" />
      <choice value="58" name="Always enabled 58" />
      <choice value="59" name="Always enabled 59" />
      <choice value="60" name="Always enabled 60" />
      <choice value="61" name="Always enabled 61" />
      <choice value="62" name="Always enabled 62" />
      <choice value="63" name="Always enabled 63" />
   </choiceOption>

   <choiceOption name="dma_chcfg1"  derivedFrom="dma_chcfg0"/>
   <choiceOption name="dma_chcfg2"  derivedFrom="dma_chcfg0"/>
   <choiceOption name="dma_chcfg3"  derivedFrom="dma_chcfg0"/>
   <choiceOption name="dma_chcfg4"  derivedFrom="dma_chcfg0"/>
   <choiceOption name="dma_chcfg5"  derivedFrom="dma_chcfg0"/>
   <choiceOption name="dma_chcfg6"  derivedFrom="dma_chcfg0"/>
   <choiceOption name="dma_chcfg7"  derivedFrom="dma_chcfg0"/>
   <choiceOption name="dma_chcfg8"  derivedFrom="dma_chcfg0"/>
   <choiceOption name="dma_chcfg9"  derivedFrom="dma_chcfg0"/>
   <choiceOption name="dma_chcfg10" derivedFrom="dma_chcfg0"/>
   <choiceOption name="dma_chcfg11" derivedFrom="dma_chcfg0"/>
   <choiceOption name="dma_chcfg12" derivedFrom="dma_chcfg0"/>
   <choiceOption name="dma_chcfg13" derivedFrom="dma_chcfg0"/>
   <choiceOption name="dma_chcfg14" derivedFrom="dma_chcfg0"/>
   <choiceOption name="dma_chcfg15" derivedFrom="dma_chcfg0"/>
   
   <template><![CDATA[
      \t// Number of DMA channels implemented
      \tstatic constexpr unsigned NumChannels = $(/DMA0/NumChannels);\n\n
      
      \tstatic constexpr uint8_t chcfg0_source  = DMAMUX_CHCFG_SOURCE($(dma_chcfg0));
      \tstatic constexpr uint8_t chcfg1_source  = DMAMUX_CHCFG_SOURCE($(dma_chcfg1));
      \tstatic constexpr uint8_t chcfg2_source  = DMAMUX_CHCFG_SOURCE($(dma_chcfg2));
      \tstatic constexpr uint8_t chcfg3_source  = DMAMUX_CHCFG_SOURCE($(dma_chcfg3));
      \tstatic constexpr uint8_t chcfg4_source  = DMAMUX_CHCFG_SOURCE($(dma_chcfg4));
      \tstatic constexpr uint8_t chcfg5_source  = DMAMUX_CHCFG_SOURCE($(dma_chcfg5));
      \tstatic constexpr uint8_t chcfg6_source  = DMAMUX_CHCFG_SOURCE($(dma_chcfg6));
      \tstatic constexpr uint8_t chcfg7_source  = DMAMUX_CHCFG_SOURCE($(dma_chcfg7));
      \tstatic constexpr uint8_t chcfg8_source  = DMAMUX_CHCFG_SOURCE($(dma_chcfg8));
      \tstatic constexpr uint8_t chcfg9_source  = DMAMUX_CHCFG_SOURCE($(dma_chcfg9));
      \tstatic constexpr uint8_t chcfg10_source = DMAMUX_CHCFG_SOURCE($(dma_chcfg10));
      \tstatic constexpr uint8_t chcfg11_source = DMAMUX_CHCFG_SOURCE($(dma_chcfg11));
      \tstatic constexpr uint8_t chcfg12_source = DMAMUX_CHCFG_SOURCE($(dma_chcfg12));
      \tstatic constexpr uint8_t chcfg13_source = DMAMUX_CHCFG_SOURCE($(dma_chcfg13));
      \tstatic constexpr uint8_t chcfg14_source = DMAMUX_CHCFG_SOURCE($(dma_chcfg14));
      \tstatic constexpr uint8_t chcfg15_source = DMAMUX_CHCFG_SOURCE($(dma_chcfg15));
   ]]></template>

   <template namespace="usbdm"><![CDATA[
      \t/** 
      \t * DMA channel numbers 
      \t */
      \tenum DmaSlot {
      \t // Channels 0-15 only
      \t   DmaSlot_Disabled                      =  0,
      \t   DmaSlot_UART0_Receive                 =  2,
      \t   DmaSlot_UART0_Transmit                =  3,
      \t   DmaSlot_UART1_Receive                 =  4,
      \t   DmaSlot_UART1_Transmit                =  5,
      \t   DmaSlot_UART2_Receive                 =  6,
      \t   DmaSlot_UART2_Transmit                =  7,
      \t   DmaSlot_I2S0_Receive                  = 12,
      \t   DmaSlot_I2S0_Transmit                 = 13,
      \t   DmaSlot_SPI0_Receive                  = 14,
      \t   DmaSlot_SPI0_Transmit                 = 15,
      \t   DmaSlot_I2C0                          = 18,
      \t   DmaSlot_I2C1_I2C2                     = 19,
      \t   DmaSlot_FTM0_Ch0                      = 20,
      \t   DmaSlot_FTM0_Ch1                      = 21,
      \t   DmaSlot_FTM0_Ch2                      = 22,
      \t   DmaSlot_FTM0_Ch3                      = 23,
      \t   DmaSlot_FTM0_Ch4                      = 24,
      \t   DmaSlot_FTM0_Ch5                      = 25,
      \t   DmaSlot_FTM0_Ch6                      = 26,
      \t   DmaSlot_FTM0_Ch7                      = 27,
      \t   DmaSlot_FTM1_Ch0                      = 28,
      \t   DmaSlot_FTM1_Ch1                      = 29,
      \t   DmaSlot_FTM2_Ch0                      = 30,
      \t   DmaSlot_FTM2_Ch1                      = 31,
      \t   DmaSlot_FTM3_Ch0                      = 32,
      \t   DmaSlot_FTM3_Ch1                      = 33,
      \t   DmaSlot_FTM3_Ch2                      = 34,
      \t   DmaSlot_FTM3_Ch3                      = 35,
      \t   DmaSlot_FTM3_Ch4                      = 36,
      \t   DmaSlot_FTM3_Ch5                      = 37,
      \t   DmaSlot_FTM3_Ch6                      = 38,
      \t   DmaSlot_FTM3_Ch7                      = 39,
      \t   DmaSlot_ADC0                          = 40,
      \t   DmaSlot_ADC1                          = 41,
      \t   DmaSlot_CMP0                          = 42,
      \t   DmaSlot_CMP1                          = 43,
      \t   DmaSlot_CMP2                          = 44,
      \t   DmaSlot_DAC0                          = 45,
      \t   DmaSlot_CMT                           = 47,
      \t   DmaSlot_PDB                           = 48,
      \t   DmaSlot_PortA                         = 49,
      \t   DmaSlot_PortB                         = 50,
      \t   DmaSlot_PortC                         = 51,
      \t   DmaSlot_PortD                         = 52,
      \t   DmaSlot_PortE                         = 53,
      \t   DmaSlot_AlwaysEnabled_54              = 54,
      \t   DmaSlot_AlwaysEnabled_55              = 55,
      \t   DmaSlot_AlwaysEnabled_56              = 56,
      \t   DmaSlot_AlwaysEnabled_57              = 57,
      \t   DmaSlot_AlwaysEnabled_58              = 58,
      \t   DmaSlot_AlwaysEnabled_59              = 59,
      \t   DmaSlot_AlwaysEnabled_60              = 60,
      \t   DmaSlot_AlwaysEnabled_61              = 61,
      \t   DmaSlot_AlwaysEnabled_62              = 62,
      \t   DmaSlot_AlwaysEnabled_63              = 63,
      \t};\n\n
   ]]></template>
</peripheralPage>

=== EgorKin/usbdm-eclipse-makefiles-build/PackageFiles/Stationery/Packages/180.ARM_Peripherals/Hardware/peripherals/sim_s32k142.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE peripheralPage SYSTEM "_menu.dtd" >
<!-- sim_s32k142.xml -->

<peripheralPage xmlns:xi="http://www.w3.org/2001/XInclude" name="_instance" description="SIM">
   
   <!-- Indicates RTC/OSC0 don't share XTAL/EXTAL pins -->
   <constant name="rtcSharesPins" value="false"   derived="true" />
   
   <!-- Oscillator used for OSC0 -->
   <constant name="osc0_peripheral"   value="/OSC0"    derived="true"/>
   
   <!-- Oscillator used for OSC1 = RTC -->
   <constant name="osc32k_peripheral" value="/RTC"     derived="true"/>
   
   <!-- RTC clock in (EXTAL32K) -->
   <constant name="rtc_clkin"         value="/RTC/osc_input_freq" derived="true"/>
   
         <intOption name="system_bus_clock." 
         units="Hz"
         description="System Bus Clock"
         toolTip="Clocks the bus slaves and peripherals\n
                  Must be &lt;= Core Clock frequency and an integer divisor"
         value="36000000" />
      
   <xi:include href="_simFiles-MK.xml"/>
   
   <template namespace="usbdm"><![CDATA[
   \t/**
   \t * RTC Clock sources
   \t */
   \tenum SimRtcClockSource {
   \t   SimRtcClockSource_SoscDiv1 = SIM_LPOCLKS_RTCCLKSEL(0),//!< SoscDiv1
   \t   SimRtcClockSource_Lpo128   = SIM_LPOCLKS_RTCCLKSEL(1),//!< Lpo128
   \t   SimRtcClockSource_RtcClkin = SIM_LPOCLKS_RTCCLKSEL(2),//!< RtcClkin
   \t   SimRtcClockSource_FircDiv1 = SIM_LPOCLKS_RTCCLKSEL(3),//!< FircDiv1
   \t};\n\n
   ]]></template>

   <template><![CDATA[
   \t/**
   \t * Set Source for RTC clock
   \t *
   \t * @param rtcClockSource
   \t */
   \tstatic void setRtcClockSource(SimRtcClockSource simRtcClockSource) {
   \t   sim().LPOCLKS = (sim().LPOCLKS&~SIM_LPOCLKS_RTCCLKSEL_MASK)|simRtcClockSource;
   \t}\n\n

   \t/**
   \t * Get RTC_CLK Clock
   \t *
   \t * @return Clock as uint32_t
   \t */
   \tstatic uint32_t getRtcFrequency() {
   \t   switch(sim().LPOCLKS&SIM_LPOCLKS_RTCCLKSEL_MASK) {
   \t      default:
   \t      case SimRtcClockSource_SoscDiv1:
   \t         return ScgInfo::getSoscDiv1Frequency();
   \t         break;
   \t      case SimRtcClockSource_Lpo128:
   \t         return ScgInfo::getLpo128Frequency();
   \t         break;
   \t      case SimRtcClockSource_RtcClkin:
   \t         return ScgInfo::getRtcClkinFrequency();
   \t         break;
   \t      case SimRtcClockSource_FircDiv1:
   \t         return ScgInfo::getFircDiv1Frequency();
   \t         break;
   \t   }
   \t}
   ]]></template>

   <template namespace="usbdm"><![CDATA[
   \t/**
   \t * LPO Clock sources
   \t */
   \tenum SimLpoClockSource {
   \t   SimLpoClockSource_Lpo128kHz = SIM_LPOCLKS_LPOCLKSEL(0),//!< Lpo128 ~ 128 kHz
   \t   SimLpoClockSource_Reserved1 = SIM_LPOCLKS_LPOCLKSEL(1),//!< Reserved
   \t   SimLpoClockSource_Lpo32kHz  = SIM_LPOCLKS_LPOCLKSEL(2),//!< Lpo32 ~ 32 kHz
   \t   SimLpoClockSource_Lpo1kHz   = SIM_LPOCLKS_LPOCLKSEL(3),//!< Lpo1 ~ 1 kHz
   \t};\n\n

   ]]></template>

   <template><![CDATA[
   \t/**
   \t * Set Source for LPO clock
   \t *
   \t * @param rtcClockSource
   \t */
   \tstatic void setLpoClockSource(SimLpoClockSource simLpoClockSource) {
   \t   sim().LPOCLKS = (sim().LPOCLKS&~SIM_LPOCLKS_LPOCLKSEL_MASK)|simLpoClockSource;
   \t}\n\n

   \t/**
   \t * Get LPO_CLK Clock
   \t *
   \t * @return Clock as uint32_t
   \t */
   \tstatic uint32_t getLpoFrequency() {
   \t   switch(sim().LPOCLKS&SIM_LPOCLKS_LPOCLKSEL_MASK) {
   \t      default:
   \t      case SimLpoClockSource_Lpo128kHz:
   \t         return ScgInfo::getLpo128Frequency();
   \t         break;
   \t      case SimLpoClockSource_Reserved1:
   \t         return 0;
   \t         break;
   \t      case SimLpoClockSource_Lpo32kHz:
   \t         return ScgInfo::getLpo128Frequency()/4;
   \t         break;
   \t      case SimLpoClockSource_Lpo1kHz:
   \t         return ScgInfo::getLpo128Frequency()/128;
   \t         break;
   \t   }
   \t}\n\n
   ]]></template>
</peripheralPage>

=== EgorKin/usbdm-eclipse-makefiles-build/PackageFiles/Stationery/Packages/180.ARM_Peripherals/Hardware/peripherals/ewm_def.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE peripheralPage SYSTEM "_menu.dtd" >
<!-- ewm_def.xml -->

<peripheralPage xmlns:xi="http://www.w3.org/2001/XInclude" name="_instance" description="External Watchdog Monitor">

   <xi:include href="_default_instance.xml"/>

   <xi:include href="_default_pcr.xml"/>
   
   <xi:include href="_mapPinsOption.xml"/>  
   
   <template><![CDATA[
      \t//! IRQ numbers for hardware
      \tstatic constexpr IRQn_Type irqNums[]  = $(_name)_IRQS;\n\n
   
      \t//! Number of IRQs for hardware
      \tstatic constexpr uint32_t irqCount  = sizeof(irqNums)/sizeof(irqNums[0]);\n\n
   ]]></template>

   <irqOption name="irqHandlingMethod"  
      description="Peripheral interrupt handler"
      toolTip="This selection allow the interrupt handler for this peripheral to be installed using several different methods"
      pattern="^WDOG%i_?$"
      classHandler="%c%i::irqHandler" />

   <!-- Template is added to class within pin_mapping.h -->
   <template><![CDATA[
       \t//! Class based callback handler has been installed in vector table\n
       \tstatic constexpr bool irqHandlerInstalled = $(irqHandlingMethod);\n\n
   ]]></template>
       
   <intOption name="irqLevel" 
      description="IRQ Level in NVIC [0-15]"
      toolTip="Sets the priority level used to configure the NVIC\n
               Lower numbers represent higher priorities"
      value="8" min="0" max="15" 
   />

   <template><![CDATA[
       \t//! Default IRQ level\n
       \tstatic constexpr uint32_t irqLevel =  $(irqLevel);\n\n
   ]]></template>
   
   <xi:include href="_clockOption.xml"/>

   <projectActionList id = "ewm_files" >
      <copy source="Project_Headers/ewm.h"          target="Project_Headers/ewm.h"          overwrite="true" derived="true" />
      <copy source="Snippets/ewm-example.cpp"       target="Snippets/ewm-example.cpp"       overwrite="true" derived="true" />
   </projectActionList>
   
   <signals/>
   
</peripheralPage>

=== EgorKin/usbdm-eclipse-makefiles-build/PackageFiles/Stationery/Packages/180.ARM_Peripherals/Hardware/peripherals/usb_clkrcv_def.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE peripheralPage SYSTEM "_menu.dtd" >
<!-- usb_clkrcv_def.xml -->
<!--
Devices using this peripheral: 
-->
<peripheralPage xmlns:xi="http://www.w3.org/2001/XInclude" name="_instance" description="USB">

   <aliasOption key="/MCG/system_usb_clkin_clock" constant="false" optional="true"/>
   <aliasOption key="/SIM/sim_sopt2_usbsrc" constant="false" optional="true"/>
   <aliasOption key="/SIM/sim_clkdiv2_usb" constant="false" optional="true"/>
   <aliasOption key="/SIM/system_usbfs_clock" optional="true"/>

   <xi:include href="usb_clkrcv.xml"/>

   <xi:include href="_irqOption.xml"/>

   <validate
      class="net.sourceforge.usbdm.deviceEditor.validators.PeripheralValidator">
   </validate>

   <xi:include href="usb_files.xml"/>

   <signals/>
</peripheralPage>
